name: Fetch Blogger Feed

on:
  # schedule:
  #   - cron: '0 */24 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Fetch Script
        run: npm start

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update feed JSON [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 🔁 Trigger Netlify Build Hook
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/68835490cd72f6d6aaba7e24
